/** @typedef {'cobol' | 'fortran' | 'haskell' | 'c' | 'assembly' | 'pascal' | 'ada'} LangId */

/**
 * Programming Language Theme Catalog
 * Personality + terminology — colors live in languages.css
 */

/** Fixed product copy — never swap this when LANGUAGE MODES change */
export const SYSTEM_COPY = {
  name: 'PeritiaOS',
  eyebrow: 'Developer Operating System',
  tagline: 'Build the System. Become the Architect.',
  description:
    'An open-source Linux distribution for engineers who want the whole stack under their hands — hardened base, declared toolchains, observability, and environment parity from first boot.',
};

/** @type {Record<LangId, object>} */
export const LANGUAGE_THEMES = {
  cobol: {
    id: 'cobol',
    name: 'COBOL',
    tagline: 'Enterprise Mainframe',
    era: '1959 →',
    scheme: 'light',
    density: 'dense',
    radius: '2px',
    personality: 'A modern banking system built on a legendary mainframe.',
    preview: {
      swatches: ['#F3EFE4', '#1F1A14', '#4A6B4A', '#C4953A'],
      motif: 'TXN',
    },
    terms: {
      sysId: 'SYS-ID',
      env: 'ENV',
      txn: 'TXN',
      region: 'CONTROL REGION',
      ready: 'READY',
      processing: 'PROCESSING',
      complete: 'COMPLETE',
      status: 'STATUS',
      record: 'RECORD',
      account: 'ACCOUNT / SYSTEM RECORD',
      batch: 'BATCH',
      message: 'SYSTEM MESSAGE',
      programId: 'PROGRAM-ID',
      workingStorage: 'WORKING-STORAGE',
      enterDocs: 'ENTER DOCS ›',
      viewSpine: 'VIEW SYSTEM SPINE',
      openDocs: 'PF12 · OPEN DOCS',
      datasetLibrary: 'DATASET LIBRARY',
      docsRegion: 'DOCS REGION',
      search: 'SEARCH DATASET...',
      spineTitle: 'OPERATING SURFACE — RECORD SET',
      spineKicker: 'System spine',
      pillarsTitle: 'THREE NON-NEGOTIABLE RETURN CODES',
      pillarsKicker: 'Design pillars',
      enterTitle: 'AUTHORIZED TRANSACTIONS',
      enterKicker: 'Enter the system',
      activityTitle: 'SYSTEM MESSAGES',
      activityKicker: 'Diagnostics',
      command: 'COMMAND =>',
      commandHint: 'ENTER TO CONTINUE',
      eoj: 'EOJ · NORMAL COMPLETION · RC=00',
      footerBrand: 'PERITIAOS · REGION PRT',
      menu: [
        { pf: 'PF1', label: 'SYSTEM', href: '#system' },
        { pf: 'PF2', label: 'PILLARS', href: '#pillars' },
        { pf: 'PF3', label: 'TRANSACTIONS', href: '#enter' },
        { pf: 'PF4', label: 'ACTIVITY', href: '#activity' },
      ],
      spineHeaders: ['REC-ID', 'MODULE', 'DESCRIPTION', 'STATUS'],
      logPrefix: 'JOB LOG · ACTIVITY',
    },
  },
  fortran: {
    id: 'fortran',
    name: 'FORTRAN',
    tagline: 'Scientific Computing',
    era: '1957 →',
    scheme: 'dark',
    density: 'dashboard',
    radius: '0px',
    personality: 'A NASA engineering workstation modernized into a contemporary application.',
    preview: {
      swatches: ['#0B1C2E', '#F4F7FB', '#3D7EA6', '#E07A3D'],
      motif: 'ITER',
    },
    terms: {
      sysId: 'RUN-ID',
      env: 'FACILITY',
      txn: 'CASE',
      region: 'NUMERICAL WORKSTATION',
      ready: 'CONVERGED',
      processing: 'ITERATING',
      complete: 'SOLVED',
      status: 'RESIDUAL',
      record: 'DATASET / OBSERVATION',
      account: 'EXPERIMENT RECORD',
      batch: 'SOLVER BATCH',
      message: 'COMPUTATION LOG',
      programId: 'PROGRAM',
      workingStorage: 'COMMON BLOCK',
      enterDocs: 'OPEN ARCHIVE ›',
      viewSpine: 'INSPECT MATRIX',
      openDocs: 'LOAD ARCHIVE',
      datasetLibrary: 'DATA ARCHIVE',
      docsRegion: 'SCIENCE REGION',
      search: 'QUERY OBSERVATIONS...',
      spineTitle: 'SYSTEM COMPONENTS — MATRIX',
      spineKicker: 'Simulation spine',
      pillarsTitle: 'CONSTRAINTS OF THE SOLVER',
      pillarsKicker: 'Numerical pillars',
      enterTitle: 'COMPUTATION PATHS',
      enterKicker: 'Select analysis',
      activityTitle: 'ITERATION TRACE',
      activityKicker: 'Solver output',
      command: 'SOLVER >',
      commandHint: 'RUN TO CONTINUE',
      eoj: 'END OF JOB · RESIDUAL < 1E-6',
      footerBrand: 'PERITIAOS · SCIENTIFIC REGION',
      menu: [
        { pf: 'F1', label: 'SYSTEM', href: '#system' },
        { pf: 'F2', label: 'PILLARS', href: '#pillars' },
        { pf: 'F3', label: 'PATHS', href: '#enter' },
        { pf: 'F4', label: 'TRACE', href: '#activity' },
      ],
      spineHeaders: ['IDX', 'MODULE', 'DESCRIPTION', 'STATE'],
      logPrefix: 'SOLVER LOG',
    },
  },
  haskell: {
    id: 'haskell',
    name: 'HASKELL',
    tagline: 'Functional & Academic',
    era: '1990 →',
    scheme: 'light',
    density: 'airy',
    radius: '12px',
    personality: 'A mathematical research environment designed by a modern product designer.',
    preview: {
      swatches: ['#F7F4FB', '#2A2438', '#5B4B8A', '#C45C9A'],
      motif: 'λ',
    },
    terms: {
      sysId: 'TERM',
      env: 'CONTEXT',
      txn: 'EXPR',
      region: 'TYPE ENVIRONMENT',
      ready: 'WHNF',
      processing: 'REDUCING',
      complete: 'NORMAL FORM',
      status: 'KIND',
      record: 'VALUE',
      account: 'BINDING · MODULE',
      batch: 'PIPELINE',
      message: 'REDUCTION TRACE',
      programId: 'MODULE',
      workingStorage: 'WHERE CLAUSE',
      enterDocs: 'Open docs →',
      viewSpine: 'Compose spine',
      openDocs: 'λ · Docs',
      datasetLibrary: 'Module library',
      docsRegion: 'Type region',
      search: 'Search terms...',
      spineTitle: 'Composition of the system',
      spineKicker: 'Spine',
      pillarsTitle: 'Laws we refuse to break',
      pillarsKicker: 'Invariants',
      enterTitle: 'Input → Map → Fold → Output',
      enterKicker: 'Pipelines',
      activityTitle: 'Reduction log',
      activityKicker: 'Trace',
      command: 'ghci>',
      commandHint: ':load Docs',
      eoj: '∀ x. RC = 0',
      footerBrand: 'PeritiaOS · λ region',
      menu: [
        { pf: '§1', label: 'System', href: '#system' },
        { pf: '§2', label: 'Laws', href: '#pillars' },
        { pf: '§3', label: 'Pipe', href: '#enter' },
        { pf: '§4', label: 'Trace', href: '#activity' },
      ],
      spineHeaders: ['Id', 'Functor', 'Description', 'Maybe'],
      logPrefix: 'Trace',
    },
  },
  c: {
    id: 'c',
    name: 'C',
    tagline: 'Systems Programming',
    era: '1972 →',
    scheme: 'dark',
    density: 'compact',
    radius: '4px',
    personality: 'A modern operating-system developer workstation.',
    preview: {
      swatches: ['#121417', '#E8E6E3', '#5F8F6B', '#3D5A73'],
      motif: '0x',
    },
    terms: {
      sysId: 'PID',
      env: 'HOST',
      txn: 'FD',
      region: 'KERNEL DEV WORKSTATION',
      ready: 'RUNNABLE',
      processing: 'SYSCALL',
      complete: 'EXIT_SUCCESS',
      status: 'STATE',
      record: 'STRUCT',
      account: 'PROCESS IMAGE',
      batch: 'JOB',
      message: 'DMSG',
      programId: 'ENTRY',
      workingStorage: 'BSS / DATA',
      enterDocs: 'open(docs) ›',
      viewSpine: 'dump spine',
      openDocs: 'man docs',
      datasetLibrary: 'INCLUDE PATH',
      docsRegion: 'USR/SHARE/DOC',
      search: 'grep docs...',
      spineTitle: 'SYSTEM OBJECTS',
      spineKicker: 'text · data · bss',
      pillarsTitle: 'NON-NEGOTIABLE CONTRACTS',
      pillarsKicker: 'ABI pillars',
      enterTitle: 'ENTRY POINTS',
      enterKicker: 'exec paths',
      activityTitle: 'DMESG',
      activityKicker: 'kernel log',
      command: '$',
      commandHint: './docs',
      eoj: 'exit 0',
      footerBrand: 'peritiaos · ring0 adjacent',
      menu: [
        { pf: '1', label: 'SYSTEM', href: '#system' },
        { pf: '2', label: 'ABI', href: '#pillars' },
        { pf: '3', label: 'EXEC', href: '#enter' },
        { pf: '4', label: 'LOG', href: '#activity' },
      ],
      spineHeaders: ['ADDR', 'SYMBOL', 'DESCRIPTION', 'STATE'],
      logPrefix: 'dmesg',
    },
  },
  assembly: {
    id: 'assembly',
    name: 'ASSEMBLY',
    tagline: 'Hardware & Machine',
    era: 'Machine',
    scheme: 'dark',
    density: 'precise',
    radius: '0px',
    personality: 'A CPU debugger transformed into a modern application.',
    preview: {
      swatches: ['#0A0A0A', '#C8C8C8', '#6F9E6F', '#D4A017'],
      motif: 'RIP',
    },
    terms: {
      sysId: 'CPU',
      env: 'MODE',
      txn: 'RIP',
      region: 'DEBUG SESSION',
      ready: 'HALT',
      processing: 'STEP',
      complete: 'RET',
      status: 'FLAGS',
      record: 'REG',
      account: 'REGISTER FILE',
      batch: 'TRACE',
      message: 'INSTRUCTION LOG',
      programId: 'IMAGE',
      workingStorage: 'STACK FRAME',
      enterDocs: 'JMP DOCS',
      viewSpine: 'DUMP SPINE',
      openDocs: 'BREAK docs',
      datasetLibrary: 'SYMBOL TABLE',
      docsRegion: 'DBG REGION',
      search: 'FIND SYM...',
      spineTitle: 'MEMORY MAP',
      spineKicker: 'Segments',
      pillarsTitle: 'HARD CONSTRAINTS',
      pillarsKicker: 'ISA rules',
      enterTitle: 'CALL TARGETS',
      enterKicker: 'Vectors',
      activityTitle: 'INSTRUCTION TRACE',
      activityKicker: 'Disasm',
      command: 'dbg>',
      commandHint: 'c · continue',
      eoj: 'ZF=1 SF=0 CF=0 · RET',
      footerBrand: 'PERITIAOS · DEBUGGER UI',
      menu: [
        { pf: 'R1', label: 'MAP', href: '#system' },
        { pf: 'R2', label: 'ISA', href: '#pillars' },
        { pf: 'R3', label: 'CALL', href: '#enter' },
        { pf: 'R4', label: 'TRACE', href: '#activity' },
      ],
      spineHeaders: ['ADDR', 'SEG', 'DESCRIPTION', 'FLAGS'],
      logPrefix: 'trace',
    },
  },
  pascal: {
    id: 'pascal',
    name: 'PASCAL',
    tagline: 'Educational Computing',
    era: '1970 →',
    scheme: 'light',
    density: 'structured',
    radius: '6px',
    personality: 'A classic computing manual turned into an interactive application.',
    preview: {
      swatches: ['#F6F1E4', '#1C2A44', '#8B5A2B', '#C46B3A'],
      motif: 'BEGIN',
    },
    terms: {
      sysId: 'UNIT',
      env: 'MODE',
      txn: 'PROC',
      region: 'STRUCTURED WORKSPACE',
      ready: 'BEGIN',
      processing: 'RUNNING',
      complete: 'END.',
      status: 'STATE',
      record: 'RECORD',
      account: 'PROGRAM HEADER',
      batch: 'CHAPTER',
      message: 'NOTE',
      programId: 'PROGRAM',
      workingStorage: 'VAR SECTION',
      enterDocs: 'Open Docs ›',
      viewSpine: 'Read Outline',
      openDocs: 'Open Manual',
      datasetLibrary: 'Units',
      docsRegion: 'Manual',
      search: 'Find in manual...',
      spineTitle: 'Program Structure',
      spineKicker: 'Outline',
      pillarsTitle: 'Rules of Structured Design',
      pillarsKicker: 'Principles',
      enterTitle: 'Chapters',
      enterKicker: 'Choose a path',
      activityTitle: 'Session Notes',
      activityKicker: 'Log',
      command: '>',
      commandHint: 'RUN',
      eoj: 'END. · Done.',
      footerBrand: 'PeritiaOS · Structured Region',
      menu: [
        { pf: '1.', label: 'System', href: '#system' },
        { pf: '2.', label: 'Rules', href: '#pillars' },
        { pf: '3.', label: 'Chapters', href: '#enter' },
        { pf: '4.', label: 'Notes', href: '#activity' },
      ],
      spineHeaders: ['No.', 'Unit', 'Description', 'State'],
      logPrefix: 'Notes',
    },
  },
  ada: {
    id: 'ada',
    name: 'ADA',
    tagline: 'Safety-Critical Engineering',
    era: '1983 →',
    scheme: 'dark',
    density: 'disciplined',
    radius: '2px',
    personality: 'A modern aerospace control system where reliability matters more than aesthetics.',
    preview: {
      swatches: ['#0E1A28', '#E8EEF4', '#4A7FA5', '#C9A227'],
      motif: 'GO',
    },
    terms: {
      sysId: 'SYS',
      env: 'MODE',
      txn: 'PKG',
      region: 'FLIGHT SOFTWARE REGION',
      ready: 'NOMINAL',
      processing: 'VERIFYING',
      complete: 'VERIFIED',
      status: 'SAFETY STATE',
      record: 'PACKAGE',
      account: 'SYSTEM STATUS BOARD',
      batch: 'MISSION',
      message: 'FAULT MONITOR',
      programId: 'PARTITION',
      workingStorage: 'PROTECTED OBJECT',
      enterDocs: 'OPEN DOCS ›',
      viewSpine: 'VERIFY SPINE',
      openDocs: 'ENTER DOCS',
      datasetLibrary: 'PACKAGE LIBRARY',
      docsRegion: 'CERT REGION',
      search: 'LOCATE PACKAGE...',
      spineTitle: 'SYSTEM PARTITION MAP',
      spineKicker: 'Partitions',
      pillarsTitle: 'VERIFICATION OBJECTIVES',
      pillarsKicker: 'Safety pillars',
      enterTitle: 'AUTHORIZED ENTRIES',
      enterKicker: 'Access paths',
      activityTitle: 'FAULT / EVENT LOG',
      activityKicker: 'Monitor',
      command: 'CMD>',
      commandHint: 'PROCEED',
      eoj: 'SAFETY STATE · NOMINAL',
      footerBrand: 'PERITIAOS · SAFETY REGION',
      menu: [
        { pf: 'P1', label: 'MAP', href: '#system' },
        { pf: 'P2', label: 'VERIFY', href: '#pillars' },
        { pf: 'P3', label: 'ENTRY', href: '#enter' },
        { pf: 'P4', label: 'FAULT', href: '#activity' },
      ],
      spineHeaders: ['PKG', 'PARTITION', 'DESCRIPTION', 'CHECK'],
      logPrefix: 'EVENT LOG',
    },
  },
};

export const LANGUAGE_ORDER = /** @type {LangId[]} */ ([
  'cobol',
  'fortran',
  'haskell',
  'c',
  'assembly',
  'pascal',
  'ada',
]);

export const DEFAULT_LANG = /** @type {LangId} */ ('cobol');
export const STORAGE_KEY = 'peritia-lang-mode';

/** @param {string | null | undefined} id */
export function resolveLanguage(id) {
  if (id && id in LANGUAGE_THEMES) return LANGUAGE_THEMES[/** @type {LangId} */ (id)];
  return LANGUAGE_THEMES[DEFAULT_LANG];
}
